defaultPortal: YOUR_PORTAL_ID
portals:
  - name: "PROD"
    portalId: YOUR_PORTAL_ID
    authType: "oauth2"
    auth:
      clientId: YOUR_CLIENT_ID
      clientSecret: YOUR_CLIENT_SECRET
      scopes:
        - "crm.objects.companies.read"
        - "crm.objects.companies.write"